#!/usr/bin/env zsh

SAVEDIFS=$IFS;

IFS=$(echo -en "\n\b");

for f in `ls -1 *\[1\]*`; do
    echo "[1]-ed file: ${f}";
    canonicalName=${f/\[1\]/}
    nonOnedFile=$(ls "${canonicalName}");

    if [[ -n "${nonOnedFile}" ]]; then
        echo "Matching original: ${nonOnedFile}";
        echo "Removing one-d file.";
        rm "${f}";
    else
        echo "No Non-oned file. Renaming oned-file to ${canonicalName}";
        mv "${f}" "${canonicalName}";
    fi

    echo "\n";
done

IFS=$SAVEDIFS;

echo "Script is done";
